# Configuration file for Appium automation framework

appium:
  server_url: "http://localhost:4723/wd/hub"
  implicit_wait_timeout: 10  # seconds
  retry_attempts: 3

device:
  id: "9xy5756xfquckj95"
  platform_name: "Android"
  platform_version: "11"

timeouts:
  action_timeout: 30  # seconds
  session_recovery_timeout: 60  # seconds

logging:
  log_level: "DEBUG"
  log_file: "automation.log"
